// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4kKB1znluYwIxrg2cz0UKYD2EaJdFU5Y',
    appId: '1:318653580866:web:2e882bc1061cd8d6fe4fdb',
    messagingSenderId: '318653580866',
    projectId: 'household-towing-system',
    authDomain: 'household-towing-system.firebaseapp.com',
    storageBucket: 'household-towing-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnrlk3KzHr5ggI-7jk0SZdqiIU_jdSS38',
    appId: '1:318653580866:android:65b78a6bf371aa76fe4fdb',
    messagingSenderId: '318653580866',
    projectId: 'household-towing-system',
    storageBucket: 'household-towing-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSUS_Oe4eEnaIhrQU34AROB_9hYvYfjy0',
    appId: '1:318653580866:ios:2a0ebd333213a938fe4fdb',
    messagingSenderId: '318653580866',
    projectId: 'household-towing-system',
    storageBucket: 'household-towing-system.firebasestorage.app',
    iosBundleId: 'com.example.householdTowingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSUS_Oe4eEnaIhrQU34AROB_9hYvYfjy0',
    appId: '1:318653580866:ios:2a0ebd333213a938fe4fdb',
    messagingSenderId: '318653580866',
    projectId: 'household-towing-system',
    storageBucket: 'household-towing-system.firebasestorage.app',
    iosBundleId: 'com.example.householdTowingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4kKB1znluYwIxrg2cz0UKYD2EaJdFU5Y',
    appId: '1:318653580866:web:c33870e17377ecaefe4fdb',
    messagingSenderId: '318653580866',
    projectId: 'household-towing-system',
    authDomain: 'household-towing-system.firebaseapp.com',
    storageBucket: 'household-towing-system.firebasestorage.app',
  );
}
